#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_OUT="$ROOT_DIR/output/repo_split_staging/surrogate-studio"
OUT_DIR="${1:-$DEFAULT_OUT}"

echo "[stage] source: $ROOT_DIR"
echo "[stage] target: $OUT_DIR"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

copy_path() {
  local rel="$1"
  local src="$ROOT_DIR/$rel"
  local dst="$OUT_DIR/$rel"
  if [[ ! -e "$src" ]]; then
    echo "[stage] missing required path: $rel" >&2
    exit 1
  fi
  mkdir -p "$(dirname "$dst")"
  if [[ -d "$src" ]]; then
    rsync -a \
      --exclude '__pycache__/' \
      --exclude '.DS_Store' \
      "$src/" "$dst/"
  else
    cp "$src" "$dst"
  fi
}

# Active runtime + app paths.
copy_path "src"
copy_path "scripts"
copy_path "schemas"
copy_path "server"

# Root files that the current app/tests/docs use directly.
copy_path "index.html"
copy_path "package.json"
copy_path "README.md"
copy_path "ARCHITECTURE_PLAN.md"
copy_path "ARCHITECTURE_SPEC_V0_1.md"
copy_path "DATASET_MODEL_TRAINER_CONTRACT.md"
copy_path "REFACTOR_GAP_MAP.md"
copy_path "REPO_SPLIT_PLAN.md"
copy_path "STORE_CONTRACT.md"
copy_path "TAB_RENDER_CONTRACT.md"
copy_path "WORKER_RUNTIME_CONTRACT.md"
copy_path "plan.txt"
copy_path "design.drawio"
copy_path "oscillator_surrogate_pipeline.py"

cat > "$OUT_DIR/.gitignore" <<'EOF'
node_modules/
output/
legacy/
__tmp_probe/
*.pyc
__pycache__/
EOF

cat > "$OUT_DIR/STAGING_NOTE.txt" <<'EOF'
This directory is an auto-generated staging snapshot for the future
`Surrogate Studio` repository.

Properties:
- keeps the current runnable layout intact
- excludes generated outputs and legacy folders
- intended for validation before `git init` / new remote creation

Generated by:
  scripts/stage_platform_repo.sh
EOF

echo "[stage] done"
echo "[stage] verify:"
echo "  cd \"$OUT_DIR\" && node scripts/test_contract_all.js"
